SHOW DATABASES;
USE TESTE;
CREATE TABLE PRODUTOS(
ID INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL, 
NOME VARCHAR(100) NOT NULL,
DESCRICAO VARCHAR(350),
PRECO DECIMAL(10,2),
QUANTIDADE INT DEFAULT (0),
DATA_ENTRADA DATE
);


