SHOW DATABASES;
USE TESTE;
SHOW TABLES;
CREATE TABLE PRODUTOS(
	ID INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL, 
	NOME VARCHAR (100) NOT NULL,
	DESCRICAO VARCHAR (350),
	PRECO DECIMAL (10,2),
	QUANTIDADE INT DEFAULT (0),
	DATA_ENTRADA DATE
);
SELECT * FROM PRODUTOS;
INSERT INTO PRODUTOS (NOME, DESCRICAO, PRECO, QUANTIDADE, DATA_ENTRADA) VALUE("ANEL DE PRATA CORACAO", "ARO DUPLO COMBINA SIMBOLISMO E ELEGANCIA", "1479.00", "10", "2025/05/30");
INSERT INTO PRODUTOS (NOME, DESCRICAO, PRECO, QUANTIDADE, DATA_ENTRADA) VALUE("COLAR DE OURO BOTANICA RADIANTE", "TRIBUTO A BELAZA DA NATUREZA, SEMELHANTE A PLANTAS", "2939.00", "10", "2025/05/30");
INSERT INTO PRODUTOS (NOME, DESCRICAO, PRECO, QUANTIDADE, DATA_ENTRADA) VALUE("BRACELETE COROA BRILHANTE", "FINALIZADO A MAO EM OURO 14K", "1719.00", "10", "2025/05/30");
UPDATE PRODUTOS SET PRECO = "1900.00" WHERE ID = 3;
UPDATE PRODUTOS SET QUANTIDADE = "25" WHERE ID = 1;
DELETE FROM PRODUTOS WHERE NOME = 'COLAR DE OURO BOTANICA RADIANTE';
SELECT * FROM PRODUTOS WHERE PRECO > 10.00;
SELECT NOME, PRECO FROM PRODUTOS WHERE PRECO > 10.00;
