SHOW DATABASES;
USE TESTE;
SHOW TABLES;
CREATE TABLE PRODUTOS(
	ID INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL, 
	NOME VARCHAR (100) NOT NULL,
	DESCRICAO VARCHAR (350),
	PRECO DECIMAL (10,2),
	QUANTIDADE INT DEFAULT (0),
	DATA_ENTRADA DATE
);
SELECT * FROM PRODUTOS;
INSERT INTO PRODUTOS (NOME, DESCRICAO, PRECO, QUANTIDADE, DATA_ENTRADA) VALUE("ANEL DE PRATA CORACAO", "ARO DUPLO COMBINA SIMBOLISMO E ELEGANCIA", "1479.00", "10", "2025/05/30");
DELETE FROM PRODUTOS WHERE ID = 2;
INSERT INTO PRODUTOS (NOME, DESCRICAO, PRECO, QUANTIDADE, DATA_ENTRADA) VALUE("COLAR DE OURO BOTANICA RADIANTE", "TRIBUTO A BELAZA DA NATUREZA, SEMELHANTE A PLANTAS", "2939.00", "10", "2025/05/30");
INSERT INTO PRODUTOS (NOME, DESCRICAO, PRECO, QUANTIDADE, DATA_ENTRADA) VALUE("BRACELETE COROA BRILHANTE", "FINALIZADO A MAO EM OURO 14K", "1719.00", "10", "2025/05/30");
